[2023-09-13T13:05:54.870+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: the_best_movies.filter_movies manual__2023-09-13T13:05:53.295314+00:00 [queued]>
[2023-09-13T13:05:54.874+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: the_best_movies.filter_movies manual__2023-09-13T13:05:53.295314+00:00 [queued]>
[2023-09-13T13:05:54.875+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-09-13T13:05:54.882+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): filter_movies> on 2023-09-13 13:05:53.295314+00:00
[2023-09-13T13:05:54.886+0000] {standard_task_runner.py:57} INFO - Started process 84 to run task
[2023-09-13T13:05:54.888+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'the_best_movies', 'filter_movies', 'manual__2023-09-13T13:05:53.295314+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/4_the_best_movies.py', '--cfg-path', '/tmp/tmplz4jgmf0']
[2023-09-13T13:05:54.892+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask filter_movies
[2023-09-13T13:05:55.153+0000] {task_command.py:415} INFO - Running <TaskInstance: the_best_movies.filter_movies manual__2023-09-13T13:05:53.295314+00:00 [running]> on host 7f15b43741c2
[2023-09-13T13:05:55.190+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='the_best_movies' AIRFLOW_CTX_TASK_ID='filter_movies' AIRFLOW_CTX_EXECUTION_DATE='2023-09-13T13:05:53.295314+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-13T13:05:53.295314+00:00'
[2023-09-13T13:05:55.200+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/4_the_best_movies.py", line 30, in filter_movies
    filter_movies_by_score_over_80(movies).filter(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2650, in to_json
    return json.to_json(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 178, in to_json
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 734, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 597, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'tmp'
[2023-09-13T13:05:55.208+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=the_best_movies, task_id=filter_movies, execution_date=20230913T130553, start_date=20230913T130554, end_date=20230913T130555
[2023-09-13T13:05:55.214+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task filter_movies (Cannot save file into a non-existent directory: 'tmp'; 84)
[2023-09-13T13:05:55.265+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-13T13:05:55.391+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
